spring:
  application:
    name: ic-gateway
  cloud:
    gateway:
      routes:
        - id: business-route
          uri: lb://ic-business
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
server:
  port: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
