server:
  port: 10001
eureka:
  instance:
    hostname: localhost
    appname: ic-eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/